FarmerCropMarketing/Controllers/MSPCropsDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FarmerCropMarketing.Models.Class;
using FarmerCropMarketing.Models.Context;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;
using FarmerCropMarketing.Models.viewmodel;
using System.IO;

namespace FarmerCropMarketing.Controllers
{
    public class MSPCropsDetailsController : Controller
    {
        
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly IWebHostEnvironment hostEnvironment;
        private readonly AppDbContext _context;

        public MSPCropsDetailsController(UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager,
            RoleManager<IdentityRole> roleManager,
            IWebHostEnvironment hostEnvironment,
            AppDbContext context)
        {

            this.userManager = userManager;
            this.signInManager = signInManager;
            this.roleManager = roleManager;
            this.hostEnvironment = hostEnvironment;
            this._context = context;
        }
        // GET: MSPCropsDetails
        public async Task<IActionResult> Index()
        {
            var x =await _context.MSPCropsDetails.ToListAsync();
            var allmspcrop = new List<editmspcrop>();
            foreach(var y in x)
                {
                var crop = new editmspcrop
                {
                    Crops_description = y.Crops_description,
                    ExistringImagePath = y.Crops_image,
                    Crops_name = y.Crops_name,
                    Crops_price = y.Crops_price,
                    Crop_Buying_End_Date = y.Crop_Buying_End_Date,
                    Crop_Buying_Staring_Date = y.Crop_Buying_Staring_Date,
                    MSPCrops_id = y.MSPCrops_id,
                    
                };
                allmspcrop.Add(crop);
            }
            return View(allmspcrop);
        }

        // GET: MSPCropsDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mSPCropsDetail = await _context.MSPCropsDetails
                .FirstOrDefaultAsync(m => m.MSPCrops_id == id);
            if (mSPCropsDetail == null)
            {
                return NotFound();
            }

            return View(mSPCropsDetail);
        }

        // GET: MSPCropsDetails/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MSPCropsDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(addmspcrop addmspcrop)
        {
            if (ModelState.IsValid)
            {
                var seller_email = User.Identity.Name;

                String uniqefileName = null;
                if (addmspcrop.Crops_image != null)
                {
                    string uplodeFolder = Path.Combine(hostEnvironment.WebRootPath, "CropImage");
                    uniqefileName = Guid.NewGuid().ToString() + "_" + addmspcrop.Crops_image.FileName;
                    string filepath = Path.Combine(uplodeFolder, uniqefileName);
                    addmspcrop.Crops_image.CopyTo(new FileStream(filepath, FileMode.Create));
                }
               var crop = new MSPCropsDetail
                {
                   Crops_image=uniqefileName,
                   Crops_name=addmspcrop.Crops_name,
                   Crops_description=addmspcrop.Crops_description,
                   Crops_price=addmspcrop.Crops_price,
                   Crop_Buying_End_Date=addmspcrop.Crop_Buying_End_Date,
                   Crop_Buying_Staring_Date=addmspcrop.Crop_Buying_Staring_Date,
                  

                };
                _context.MSPCropsDetails.Add(crop);
                await _context.SaveChangesAsync();

                ViewBag.mes = "Your Crop is Added ";
                return View();
            }
            return View(addmspcrop);

        }

        // GET: MSPCropsDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mSPCropsDetail = await _context.MSPCropsDetails.FindAsync(id);

            if (mSPCropsDetail == null)
            {
                return NotFound();
            }
            var crop = new editmspcrop
            {
                ExistringImagePath = mSPCropsDetail.Crops_image,
                Crops_name = mSPCropsDetail.Crops_name,
                Crops_description = mSPCropsDetail.Crops_description,
                Crops_price = mSPCropsDetail.Crops_price,
                Crop_Buying_End_Date = mSPCropsDetail.Crop_Buying_End_Date,
                Crop_Buying_Staring_Date = mSPCropsDetail.Crop_Buying_Staring_Date,
                MSPCrops_id=mSPCropsDetail.MSPCrops_id,

            };
            return View(crop);
        }

        // POST: MSPCropsDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Edit(int id, editmspcrop editmspcrop)
        {
            if (id != editmspcrop.MSPCrops_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                  
                    var curentcrop =await _context.MSPCropsDetails.Where(x => x.MSPCrops_id == id).FirstOrDefaultAsync();
                    curentcrop.Crops_description = editmspcrop.Crops_description;
                    curentcrop.Crops_name = editmspcrop.Crops_name;
                    curentcrop.Crops_price = editmspcrop.Crops_price;
                    curentcrop.Crop_Buying_End_Date = editmspcrop.Crop_Buying_End_Date;
                    curentcrop.Crop_Buying_Staring_Date = editmspcrop.Crop_Buying_Staring_Date;
                    if (editmspcrop.Crops_image != null)
                    {
                        string filepath = Path.Combine(hostEnvironment.WebRootPath,
                            "CropImage", editmspcrop.ExistringImagePath);
                        System.IO.File.Delete(filepath);
                        curentcrop.Crops_image = updateimage(editmspcrop);
                    }



                    _context.Update(curentcrop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MSPCropsDetailExists(editmspcrop.MSPCrops_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(editmspcrop);
        }
        public string updateimage(editmspcrop editmspcrop)
        {
            string uniqname = null;
            if(editmspcrop.Crops_image!=null)
            {
                string uplodeFolder = Path.Combine(hostEnvironment.WebRootPath, "CropImage");
                uniqname = Guid.NewGuid().ToString() + "_" + editmspcrop.Crops_image.FileName;
                string filepath = Path.Combine(uplodeFolder, uniqname);
                editmspcrop.Crops_image.CopyTo(new FileStream(filepath, FileMode.Create));

            }
            return uniqname;
        }
        // GET: MSPCropsDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mSPCropsDetail = await _context.MSPCropsDetails
                .FirstOrDefaultAsync(m => m.MSPCrops_id == id);
            if (mSPCropsDetail == null)
            {
                return NotFound();
            }

            return View(mSPCropsDetail);
        }

        // POST: MSPCropsDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mSPCropsDetail = await _context.MSPCropsDetails.FindAsync(id);
            _context.MSPCropsDetails.Remove(mSPCropsDetail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MSPCropsDetailExists(int id)
        {
            return _context.MSPCropsDetails.Any(e => e.MSPCrops_id == id);
        }
    }
}

FarmerCropMarketing/Views/Shared/H_Layout.cshtml
<!DOCTYPE html>
@inject SignInManager<IdentityUser> signinmanager
@inject UserManager<IdentityUser> usemanager

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]LMS - Login</title>
    
    <link rel="stylesheet" href="~/css/HomePage.css" />


</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @RenderSection("Scripts", required: false)
 
</body>
</html>

FarmerCropMarketing/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@inject SignInManager<IdentityUser> signinmanager
@inject UserManager<IdentityUser> usemanager

<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <title>@ViewData["Title"] - Leave_Management_System</title>

    <link rel="stylesheet" href="~/css/DashBoard.css" />
</head>
<body>

    <div id="wrapper">
        <div class="overlay"></div>

        <!-- Sidebar -->
        <nav class="fixed-top align-top" id="sidebar-wrapper" role="navigation">
            <div class="simplebar-content" style="padding: 0px;">
                <a class="sidebar-brand" asp-controller="Home" asp-action="Index">
                    <span class="align-middle">Farmer Crop Marketing</span>
                </a>

                <ul class="navbar-nav align-self-stretch">

                    @if (signinmanager.IsSignedIn(User))
                    {
                @if (User.IsInRole("Admin"))
                {
                <li class="nav-link text-left">
                    <a class="" asp-area="" asp-controller="admin" asp-action="UserList">Manage User</a>
                </li>
                                    <li class="nav-link text-left">
                                        <a class="" asp-area="" asp-controller="Admin" asp-action="CropList">Manage Crope</a>
                                    </li>
}
                                @if (User.IsInRole("Government"))
                                {
                <li class="nav-link text-left">
                    <a class="nav-link text-left " asp-area="" asp-controller="MSPCropsDetails" asp-action="Create">Add Crop in MSP</a>
                </li>
                                    <li class="nav-link text-left">
                                        <a class="" asp-area="" asp-controller="MSPCropsDetails" asp-action="">All MSP Crope</a>
                                    </li>}
                                                @if (User.IsInRole("Farmer"))
                                                {
                                <li class="nav-link text-left">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Farmers" asp-action="HomepageFarmer">Home</a>
                                </li>
                                                    <li class="nav-link text-left">
                                                        <a class="" asp-area="" asp-controller="Farmers" asp-action="mybuyitem">My Buy  Crope</a>
                                                    </li>
                                                                        <li class="nav-link text-left">
                                                                            <a class="" asp-area="" asp-controller="Farmers" asp-action="AddNewCrop">Crop Buy Or Sell</a>
                                                                        </li>
                                                                                            
                                                                                                                <li class="nav-link text-left">
                                                                                                                    <a class="" asp-area="" asp-controller="Farmers" asp-action="MyCart">My Cart</a>
                                                                                                                </li>
                                                                                                                                    <li class="nav-link text-left">
                                                                                                                                        <a class="" asp-area="" asp-controller="Farmers" asp-action="sellinmsp">MSP Crop</a>
                                                                                                                                    </li>
                                                                                                                                                        <li class="nav-link text-left">
                                                                                                                                                            <a class="" asp-area="" asp-controller="Farmers" asp-action="mysellitem"> My Sell item</a>
                                                                                                                                                        </li>
                                                                                                                                                        }}

                </ul>
                <ul class="navbar-nav  align-self-stretch">

                    @if (signinmanager.IsSignedIn(User))
                    {

        <li class="nav-item">
            <a class="nav-link text-left active" role="button" aria-haspopup="true" aria-expanded="false" asp-area="" asp-page="" title="Manage"> <i class="flaticon-bar-chart-1">@User.Identity.Name</i></a>

        </li>

                        <li class="nav-item">
                            <form class="nav-link text-left " asp-controller="account" asp-action="Logout">
                                <button type="submit" class="btn btn-block btn-dark">Logout</button>
                            </form>
                        </li>
 }
                    else
                    {
        <li class="">
            <a class="nav-link text-left " role="button" aria-haspopup="true" aria-expanded="false" asp-controller="account" asp-action="login">Login</a>
        </li>

                        <li class="">
                            <a class="nav-link text-left " role="button" aria-haspopup="true" aria-expanded="false" asp-controller="account" asp-action="register">Register</a>
                        </li>
}
                </ul>


            </div>


        </nav>
        <div id="page-content-wrapper">


            <div id="content">

                <div class="container-fluid p-0 px-lg-0 px-md-0">
                    <!-- Topbar -->
                    <nav class="navbar navbar-expand navbar-light my-navbar">

                        <!-- Sidebar Toggle (Topbar) -->
                        <div type="button" id="bar" class="nav-icon1 hamburger animated fadeInLeft is-closed" data-toggle="offcanvas">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown  d-sm-none">
                            </li>

                            <li class="nav-item dropdown">

                                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown">
                                    <span class="mr-2 d-none d-lg-inline text-gray-600 small"> @User.Identity.Name</span>
                                </a>

                            </li>

                        </ul>

                    </nav>


                </div>
                @RenderBody()






                <footer class="footer" style="margin-top:100px">
                    <div class="container-fluid">
                        <div class="row text-muted">
                            <div class="col-6 text-left">
                                <p class="mb-0">
                                    <a href="index.html" class="text-muted"><strong>Farmer Crop Marketing</strong></a> &copy
                                </p>
                            </div>
                            <div class="col-6 text-right">
                                <ul class="list-inline">

                                    <li class="footer-item">
                                        <a class="text-muted" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </footer>

            </div>
        </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>


    <script>
        $('#bar').click(function () {
            $(this).toggleClass('open');
            $('#page-content-wrapper ,#sidebar-wrapper').toggleClass('toggled');

        });
    </script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>