FarmerCropMarketing/Models/Class/Farmers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FarmerCropMarketing.Models
{
    public class Farmers
    {
        [Key]
        public int Farmers_id { get; set; }

        [Required]
        [Display(Name = "Name")]
        public String Farmers_name { get; set; }
        [Required]
        [Display(Name = "Email Address")]
        [EmailAddress(ErrorMessage = "please enter valid email ")]
        public String Farmers_email { get; set; }
        
        [Required]
        [Display(Name = "Mobile number")]
        [DataType(DataType.Text)]
        public string Farmers_mobile_no { get; set; }
        [Required]
        [Display(Name = "Address")]
        [DataType(DataType.MultilineText)]
        public string Farmers_address { get; set; }

        public String Farmers_image { get; set; }

        public IList<Cart> Cart { get; set; }
        public IList<Crops> Crops { get; set; }


    }
}

FarmerCropMarketing/Models/viewmodel/addnewCrop.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FarmerCropMarketing.Models.viewmodel
{
    public class addnewCrop
    {
        public int crop_id { get; set; }
        [Required]
        [Display(Name = "Crop Name")]
        public String crop_name { get; set; }
        [Required]
        [Display(Name = "Quantity")]
        public int crop_quantity { get; set; }
        [Required]
        [Display(Name = "Price")]
        public int crop_price { get; set; }
        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Description ")]
        public String crop_description { get; set; }
        
        [Display(Name = "You Want To Sell this Crop")]
        public bool youwanttosell { get; set; }

        [Required]
        [Display(Name = "Crop image")]
        public IFormFile crop_image { get; set; }

    }
}

FarmerCropMarketing/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FarmerCropMarketing.Models;
using FarmerCropMarketing.Models.Context;

namespace FarmerCropMarketing.Controllers
{
    public class CartsController : Controller
    {
        private readonly AppDbContext _context;

        public CartsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Carts
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Cart.Include(c => c.Crops).Include(c => c.Farmers);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Carts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart
                .Include(c => c.Crops)
                .Include(c => c.Farmers)
                .FirstOrDefaultAsync(m => m.Cart_id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // GET: Carts/Create
        public IActionResult Create()
        {
            ViewData["Crops_id"] = new SelectList(_context.Crops, "Crops_id", "Crops_description");
            ViewData["Farmers_id"] = new SelectList(_context.Farmers, "Farmers_id", "Farmers_address");
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Cart_id,Farmers_id,Crops_id")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Crops_id"] = new SelectList(_context.Crops, "Crops_id", "Crops_description", cart.Crops_id);
            ViewData["Farmers_id"] = new SelectList(_context.Farmers, "Farmers_id", "Farmers_address", cart.Farmers_id);
            return View(cart);
        }

        // GET: Carts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }
            ViewData["Crops_id"] = new SelectList(_context.Crops, "Crops_id", "Crops_description", cart.Crops_id);
            ViewData["Farmers_id"] = new SelectList(_context.Farmers, "Farmers_id", "Farmers_address", cart.Farmers_id);
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Cart_id,Farmers_id,Crops_id")] Cart cart)
        {
            if (id != cart.Cart_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.Cart_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Crops_id"] = new SelectList(_context.Crops, "Crops_id", "Crops_description", cart.Crops_id);
            ViewData["Farmers_id"] = new SelectList(_context.Farmers, "Farmers_id", "Farmers_address", cart.Farmers_id);
            return View(cart);
        }

        // GET: Carts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }
            _context.Cart.Remove(cart);
            await _context.SaveChangesAsync();
            return RedirectToAction("mycart","Farmers");
            
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cart = await _context.Cart.FindAsync(id);
            _context.Cart.Remove(cart);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartExists(int id)
        {
            return _context.Cart.Any(e => e.Cart_id == id);
        }
    }
}

FarmerCropMarketing/Controllers/CropsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FarmerCropMarketing.Models;
using FarmerCropMarketing.Models.Context;

namespace FarmerCropMarketing.Controllers
{
    public class CropsController : Controller
    {
        private readonly AppDbContext _context;

        public CropsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Crops
        public async Task<IActionResult> Index()
        {
            return View(await _context.Crops.ToListAsync());
        }

        // GET: Crops/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crops = await _context.Crops
                .FirstOrDefaultAsync(m => m.Crops_id == id);
            if (crops == null)
            {   
                return NotFound();
            }

            return View(crops);
        }

        // GET: Crops/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Crops/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Crops_id,Crops_name,Crops_quantity,Crops_price,Crops_description,Crops_image,Farmers_id")] Crops crops)
        {
            if (ModelState.IsValid)
            {
                _context.Add(crops);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(crops);
        }

        // GET: Crops/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crops = await _context.Crops.FindAsync(id);
            if (crops == null)
            {
                return NotFound();
            }
            return View(crops);
        }

        // POST: Crops/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Crops_id,Crops_name,Crops_quantity,Crops_price,Crops_description,Crops_image,Farmers_id")] Crops crops)
        {
            if (id != crops.Crops_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(crops);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CropsExists(crops.Crops_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(crops);
        }

        // GET: Crops/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crops = await _context.Crops
                .FirstOrDefaultAsync(m => m.Crops_id == id);
            if (crops == null)
            {
                return NotFound();
            }

            return View(crops);
        }

        // POST: Crops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var crops = await _context.Crops.FindAsync(id);
            _context.Crops.Remove(crops);
            await _context.SaveChangesAsync();
            return RedirectToAction("CropList", "Admin");
        }

        private bool CropsExists(int id)
        {
            return _context.Crops.Any(e => e.Crops_id == id);
        }
    }
}

FarmerCropMarketing/Views/Farmers/AddNewCrop.cshtml
@model FarmerCropMarketing.Models.viewmodel.addnewCrop
<h1>Add new Crop </h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="AddNewCrop">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="crop_name" class="control-label"></label>
                <input asp-for="crop_name" class="form-control" />
                <span asp-validation-for="crop_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="crop_price" class="control-label"></label>
                <input asp-for="crop_price" class="form-control" />
                <span asp-validation-for="crop_price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="crop_quantity" class="control-label"></label>
                <input asp-for="crop_quantity" class="form-control" />
                <span asp-validation-for="crop_quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="crop_description" class="control-label"></label>
                <textarea asp-for="crop_description" class="form-control"></textarea>
                <span asp-validation-for="crop_description" class="text-danger"></span>
            </div>
            <div class="form-group">

                <label asp-for="crop_image" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="crop_image" class="form-control custom-file-input" />
                    <label class="custom-file-label">Product image</label>
                </div>
                <span asp-validation-for="crop_image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="youwanttosell" class="control-label"></label>
                <input asp-for="youwanttosell" class="form-control" /><br>
                <div style="font-size=11px;">If you want to buy this crop pleae don`t check this check box</div>
                <span asp-validation-for="youwanttosell" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>



@section Scripts {
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var filename = $(this).val().split("\\").pop();
                $(this).next(".custom-file-label").html(filename);
            });

        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FarmerCropMarketing/Views/Farmers/Create.cshtml
@model FarmerCropMarketing.Models.Farmers

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Farmers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Farmers_name" class="control-label"></label>
                <input asp-for="Farmers_name" class="form-control" />
                <span asp-validation-for="Farmers_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Farmers_email" class="control-label"></label>
                <input asp-for="Farmers_email" class="form-control" />
                <span asp-validation-for="Farmers_email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Farmers_mobile_no" class="control-label"></label>
                <input asp-for="Farmers_mobile_no" class="form-control" />
                <span asp-validation-for="Farmers_mobile_no" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Farmers_address" class="control-label"></label>
                <textarea asp-for="Farmers_address" class="form-control"></textarea>
                <span asp-validation-for="Farmers_address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Farmers_image" class="control-label"></label>
                <input asp-for="Farmers_image" class="form-control" />
                <span asp-validation-for="Farmers_image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FarmerCropMarketing/Views/Farmers/Delete.cshtml
@model FarmerCropMarketing.Models.Farmers

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Farmers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Farmers_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Farmers_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Farmers_email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Farmers_email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Farmers_mobile_no)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Farmers_mobile_no)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Farmers_address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Farmers_address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Farmers_image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Farmers_image)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Farmers_id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FarmerCropMarketing/Views/Farmers/Details.cshtml
@model FarmerCropMarketing.Models.Farmers

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Farmers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Farmers_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Farmers_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Farmers_email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Farmers_email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Farmers_mobile_no)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Farmers_mobile_no)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Farmers_address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Farmers_address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Farmers_image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Farmers_image)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Farmers_id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FarmerCropMarketing/Views/Farmers/Edit.cshtml
@model FarmerCropMarketing.Models.Farmers

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Farmers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Farmers_id" />
            <div class="form-group">
                <label asp-for="Farmers_name" class="control-label"></label>
                <input asp-for="Farmers_name" class="form-control" />
                <span asp-validation-for="Farmers_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Farmers_email" class="control-label"></label>
                <input asp-for="Farmers_email" class="form-control" />
                <span asp-validation-for="Farmers_email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Farmers_mobile_no" class="control-label"></label>
                <input asp-for="Farmers_mobile_no" class="form-control" />
                <span asp-validation-for="Farmers_mobile_no" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Farmers_address" class="control-label"></label>
                <textarea asp-for="Farmers_address" class="form-control"></textarea>
                <span asp-validation-for="Farmers_address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Farmers_image" class="control-label"></label>
                <input asp-for="Farmers_image" class="form-control" />
                <span asp-validation-for="Farmers_image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FarmerCropMarketing/Views/Farmers/HomepageFarmer.cshtml
@model IEnumerable<FarmerCropMarketing.Models.Crops>

@{
    ViewData["Title"] = "Home Page";
}

@{
    var i = 0;
}

<div class="container">
    @foreach (var item in Model)
    {
        var crop_image_path = "/CropImage/" + item.Crops_image;

        @if (!item.itComplited)
        {
            <div style="display:inline-block">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="@crop_image_path" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">@Html.DisplayFor(modelItem => item.Crops_name)</h5>
                        <p class="card-text"> @Html.DisplayNameFor(model => model.Crops_price) : @Html.DisplayFor(modelItem => item.Crops_price)</p>
                        |
                        <a asp-action="Details" asp-controller="Crops" asp-route-id="@item.Crops_id" class="btn btn-primary">Details</a> |
                        @if (item.buyOrsell)
                        {
                            <a asp-action="Buy" asp-route-id="@item.Crops_id" class="btn btn-primary">Buy</a>
                        }
                        else
                        {
                            <a asp-action="Sell" asp-route-id="@item.Crops_id" class="btn btn-success">Sell</a>
                        }
                    </div>
                </div>
            </div>

            i++;
        }
    }

FarmerCropMarketing/Views/Farmers/Index.cshtml
@model IEnumerable<FarmerCropMarketing.Models.Farmers>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Farmers_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Farmers_email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Farmers_mobile_no)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Farmers_address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Farmers_image)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Farmers_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Farmers_email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Farmers_mobile_no)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Farmers_address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Farmers_image)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Farmers_id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Farmers_id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Farmers_id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

FarmerCropMarketing/Views/Farmers/MyCart.cshtml
@model IEnumerable<FarmerCropMarketing.Models.Cart>

@{
    ViewData["Title"] = "MyCart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>MyCart</h1>
<h3>Total Price @ViewBag.price</h3>
<a asp-action="placeorder" asp-controller="Farmers">Place Order </a>
<table class="table text-center" >
    <thead>
        <tr>
            <th scope="col"> @Html.DisplayNameFor(model => model.Crops.Crops_name)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Crops.Crops_price)</th>
            <th scope="col"> @Html.DisplayNameFor(model => model.Crops.Crops_image)</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
       

        @foreach (var item in Model)
        {
            var crop_image_path = "/CropImage/" + item.Crops.Crops_image;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Crops.Crops_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Crops.Crops_price)
                </td>
                <td>
                    <img class="img-thumbnail" height="150" width="150" src="@crop_image_path" alt="Card image cap">
                </td>
                <td>

                    <a class="btn btn-warning" asp-action="Delete" asp-controller="Carts" asp-route-id="@item.Cart_id">Remove Frome Cart</a>
                </td>
            </tr>
        }
    </tbody>

</table>

FarmerCropMarketing/Views/Farmers/SellCropInMSP.cshtml
@model FarmerCropMarketing.Models.Class.MSPSellCrops
@{
    ViewData["Title"] = "Sell Item In Msp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="SellCropInMSP" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Farmers_id" />
            <input type="hidden" asp-for="MSPCrops_id" />
            <div class="form-group">
                <label asp-for="Crops_quantity" class="control-label"></label>
                <input asp-for="Crops_quantity" class="form-control" />
                <span asp-validation-for="Crops_quantity" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Farmers.Farmers_address" class="control-label"></label>
                <input asp-for="Farmers.Farmers_address" class="form-control" />
                <span asp-validation-for="Farmers.Farmers_address" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="MSPCropsDetail.Crops_name" class="control-label"></label>
                <input asp-for="MSPCropsDetail.Crops_name" class="form-control" disabled />
                <span asp-validation-for="MSPCropsDetail.Crops_name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="MSPCropsDetail.Crops_price" class="control-label"></label>
                <input asp-for="MSPCropsDetail.Crops_price" class="form-control" disabled />
                <span asp-validation-for="MSPCropsDetail.Crops_price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="MSPCropsDetail.Crops_description" class="control-label"></label>
                <input asp-for="MSPCropsDetail.Crops_description" class="form-control" disabled />
                <span asp-validation-for="MSPCropsDetail.Crops_description" class="text-danger"></span>
            </div>

            @{
                var imagepath = "../../CropImage/" + (Model.MSPCropsDetail.Crops_image);
            }
            <div class="form-group row col-4 offset-4">
                <img src="@imagepath" class="img-thumbnail">
            </div>
            @*@imagepath*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var filename = $(this).val().split("\\").pop();
                $(this).next(".custom-file-label").html(filename);
            });

        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}